version: '3.8'

services:
  nodeserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
  
  nginx:
    restart: always
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    
